apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    orgId: 1
    url: http://bvolt-influxdb:8086
    jsonData:
      version: Flux
      organization: bvolt
      defaultBucket: bvolt_dev
    secureJsonData:
      token: ${INFLUX_GRAFANA_TOKEN}
    isDefault: true
